// UCLA Department List for Course Selection Dropdown
export const departments = [
  { name: "Aerospace Studies", code: "AERO ST" },
  { name: "African American Studies", code: "AF AMER" },
  { name: "African Studies", code: "AF ST" },
  { name: "American Indian Studies", code: "AM IND" },
  { name: "American Sign Language", code: "ASL" },
  { name: "Ancient Near East", code: "AN NEAST" },
  { name: "Anesthesiology", code: "ANESTH" },
  { name: "Anthropology", code: "ANTHRO" },
  { name: "Applied Chemical Sciences", code: "APP CHM" },
  { name: "Arabic", code: "ARABIC" },
  { name: "Archaeology", code: "ARCHY" },
  { name: "Architecture and Urban Design", code: "ARCH&UD" },
  { name: "Armenian", code: "ARMEN" },
  { name: "Art", code: "ART" },
  { name: "Art History", code: "ART HIS" },
  { name: "Arts and Architecture", code: "ART&ARCH" },
  { name: "Arts Education", code: "ART ED" },
  { name: "Asian", code: "ASIAN" },
  { name: "Asian American Studies", code: "AS AM" },
  { name: "Astronomy", code: "ASTR" },
  { name: "Atmospheric and Oceanic Sciences", code: "ATMOS" },
  { name: "Bioengineering", code: "BIOENGR" },
  { name: "Bioinformatics (Graduate)", code: "BIOINFO" },
  { name: "Bioinformatics (Undergraduate)", code: "BIOINFO" },
  { name: "Biological Chemistry", code: "BIOL CH" },
  { name: "Biomathematics", code: "BIOMATH" },
  { name: "Biomedical Research", code: "BIOMED" },
  { name: "Biostatistics", code: "BIOSTAT" },
  { name: "Bulgarian", code: "BULGAR" },
  { name: "Central and East European Studies", code: "CEEUR" },
  { name: "Chemical Engineering", code: "CH ENGR" },
  { name: "Chemistry and Biochemistry", code: "CHEM" },
  { name: "Chicana/o and Central American Studies", code: "CHICANO" },
  { name: "Chinese", code: "CHIN" },
  { name: "Civil and Environmental Engineering", code: "C&EE" },
  { name: "Classics", code: "CLASSIC" },
  { name: "Clusters", code: "CLUSTER" },
  { name: "Communication", code: "COMM" },
  { name: "Community Engagement and Social Change", code: "CESC" },
  { name: "Community Health Sciences", code: "CHS" },
  { name: "Comparative Literature", code: "COM LIT" },
  { name: "Computational and Systems Biology", code: "CSB" },
  { name: "Computer Science", code: "COM SCI" },
  { name: "Conservation of Cultural Heritage", code: "CCH" },
  { name: "Czech", code: "CZECH" },
  { name: "Dance", code: "DANCE" },
  { name: "Data Science in Biomedicine", code: "DSB" },
  { name: "Dentistry", code: "DENT" },
  { name: "Design / Media Arts", code: "DESMA" },
  { name: "Digital Humanities", code: "DH" },
  { name: "Disability Studies", code: "DIS ST" },
  { name: "Dutch", code: "DUTCH" },
  { name: "Earth, Planetary, and Space Sciences", code: "EPS SCI" },
  { name: "East Asian Studies", code: "EAS" },
  { name: "Ecology and Evolutionary Biology", code: "EE BIOL" },
  { name: "Economics", code: "ECON" },
  { name: "Education", code: "EDUC" },
  { name: "Electrical and Computer Engineering", code: "ECE ENGR" },
  { name: "Engineering", code: "ENGR" },
  { name: "English", code: "ENGL" },
  { name: "English as A Second Language", code: "ESL" },
  { name: "English Composition", code: "ENG COMP" },
  { name: "Environment", code: "ENV" },
  { name: "Environmental Health Sciences", code: "ENV HLT" },
  { name: "Epidemiology", code: "EPIDEM" },
  { name: "Ethnomusicology", code: "ETHNOMU" },
  { name: "European Languages and Transcultural Studies", code: "ELTS" },
  { name: "Family Medicine", code: "FAM MED" },
  { name: "Fiat Lux", code: "FIAT LUX" },
  { name: "Filipino", code: "FILIPNO" },
  { name: "Film and Television", code: "FILM TV" },
  { name: "Food Studies", code: "FOOD ST" },
  { name: "French", code: "FRENCH" },
  { name: "Gender Studies", code: "GENDER" },
  { name: "Geography", code: "GEOG" },
  { name: "German", code: "GERMAN" },
  { name: "Gerontology", code: "GERON" },
  { name: "Global Health", code: "GLBL HLT" },
  { name: "Global Jazz Studies", code: "GLBL JAZZ" },
  { name: "Global Studies", code: "GLBL ST" },
  { name: "Graduate Student Professional Development", code: "GSPD" },
  { name: "Greek", code: "GREEK" },
  { name: "Health Policy and Management", code: "HPM" },
  { name: "Healthcare Administration", code: "HCA" },
  { name: "Hebrew", code: "HEBREW" },
  { name: "Hindi-Urdu", code: "HINDI" },
  { name: "History", code: "HIST" },
  { name: "Honors Collegium", code: "HONORS" },
  { name: "Human Genetics", code: "HUM GEN" },
  { name: "Hungarian", code: "HUNG" },
  { name: "Indigenous Languages of the Americas", code: "ILA" },
  { name: "Indo-European Studies", code: "INDO EUR" },
  { name: "Indonesian", code: "INDONES" },
  { name: "Information Studies", code: "INFO" },
  { name: "International and Area Studies", code: "INTL" },
  { name: "International Development Studies", code: "INTL DEV" },
  { name: "International Migration Studies", code: "INTL MIG" },
  { name: "Iranian", code: "IRANIAN" },
  { name: "Islamic Studies", code: "ISLAMIC" },
  { name: "Italian", code: "ITALIAN" },
  { name: "Japanese", code: "JAPAN" },
  { name: "Jewish Studies", code: "JEWISH" },
  { name: "Korean", code: "KOREAN" },
  { name: "Labor Studies", code: "LABOR" },
  { name: "Latin", code: "LATIN" },
  { name: "Latin American Studies", code: "LAT AM" },
  { name: "Law", code: "LAW" },
  { name: "Law (Undergraduate)", code: "LAW UG" },
  { name: "Lesbian, Gay, Bisexual, Transgender, and Queer Studies", code: "LGBTQS" },
  { name: "Life Sciences", code: "LIFESCI" },
  { name: "Linguistics", code: "LING" },
  { name: "Lithuanian", code: "LITH" },
  { name: "Management", code: "MGMT" },
  { name: "Management-Executive MBA", code: "MGMT EMBA" },
  { name: "Management-Full-Time MBA", code: "MGMT FTMBA" },
  { name: "Management-Fully Employed MBA", code: "MGMT FEMBA" },
  { name: "Management-Global Executive MBA Asia Pacific", code: "MGMT GEMBA" },
  { name: "Management-Master of Financial Engineering", code: "MGMT MFE" },
  { name: "Management-Master of Science in Business Analytics", code: "MGMT MSBA" },
  { name: "Management-PhD", code: "MGMT PHD" },
  { name: "Materials Science and Engineering", code: "MAT SCI" },
  { name: "Mathematics", code: "MATH" },
  { name: "Mechanical and Aerospace Engineering", code: "MECH&AE" },
  { name: "Medical History", code: "MED HIST" },
  { name: "Medicine", code: "MED" },
  { name: "Microbiology, Immunology, and Molecular Genetics", code: "MICRO" },
  { name: "Middle Eastern Studies", code: "MIDDLE E" },
  { name: "Military Science", code: "MIL SCI" },
  { name: "Molecular and Medical Pharmacology", code: "MOL PHARM" },
  { name: "Molecular Biology", code: "MOL BIO" },
  { name: "Molecular Toxicology", code: "MOL TOX" },
  { name: "Molecular, Cell, and Developmental Biology", code: "MCDB" },
  { name: "Molecular, Cellular, and Integrative Physiology", code: "MCIP" },
  { name: "Music", code: "MUSIC" },
  { name: "Music Industry", code: "MUS IND" },
  { name: "Musicology", code: "MUSICOL" },
  { name: "Naval Science", code: "NAV SCI" },
  { name: "Near Eastern Languages", code: "NEAR E" },
  { name: "Neurobiology", code: "NEURO" },
  { name: "Neurology", code: "NEUROL" },
  { name: "Neuroscience", code: "NEURO" },
  { name: "Neuroscience (Graduate)", code: "NEURO GR" },
  { name: "Neurosurgery", code: "NEUROSURG" },
  { name: "Nursing", code: "NURSING" },
  { name: "Obstetrics and Gynecology", code: "OBGYN" },
  { name: "Ophthalmology", code: "OPHTHAL" },
  { name: "Oral Biology", code: "ORAL BIO" },
  { name: "Orthopaedic Surgery", code: "ORTHOP" },
  { name: "Pathology and Laboratory Medicine", code: "PATH" },
  { name: "Pediatrics", code: "PEDS" },
  { name: "Philosophy", code: "PHILOS" },
  { name: "Physics", code: "PHYSICS" },
  { name: "Physics and Biology in Medicine", code: "PBM" },
  { name: "Physiological Science", code: "PHYSCI" },
  { name: "Physiology", code: "PHYSIOL" },
  { name: "Polish", code: "POLISH" },
  { name: "Political Science", code: "POL SCI" },
  { name: "Portuguese", code: "PORT" },
  { name: "Program in Computing", code: "PIC" },
  { name: "Psychiatry and Biobehavioral Sciences", code: "PSYCH" },
  { name: "Psychology", code: "PSYCH" },
  { name: "Public Affairs", code: "PUB AFF" },
  { name: "Public Health", code: "PUB HLT" },
  { name: "Public Policy", code: "PUB POL" },
  { name: "Quantum Science and Technology", code: "QST" },
  { name: "Radiation Oncology", code: "RAD ONC" },
  { name: "Radiological Science", code: "RAD SCI" },
  { name: "Religion, Study of", code: "RELIGN" },
  { name: "Research Practice", code: "RES PRAC" },
  { name: "Romanian", code: "ROMAN" },
  { name: "Russian", code: "RUSSIAN" },
  { name: "Scandinavian", code: "SCAND" },
  { name: "Science Education", code: "SCI ED" },
  { name: "Semitic", code: "SEMITIC" },
  { name: "Serbian/Croatian", code: "SERB" },
  { name: "Slavic", code: "SLAVIC" },
  { name: "Social Science", code: "SOC SCI" },
  { name: "Social Thought", code: "SOC THT" },
  { name: "Social Welfare", code: "SOC WEL" },
  { name: "Society and Genetics", code: "SOC&GEN" },
  { name: "Sociology", code: "SOC" },
  { name: "South Asian", code: "S ASIAN" },
  { name: "Southeast Asian", code: "SE ASIAN" },
  { name: "Spanish", code: "SPANISH" },
  { name: "Statistics", code: "STATS" },
  { name: "Surgery", code: "SURGERY" },
  { name: "Swahili", code: "SWAHILI" },
  { name: "Thai", code: "THAI" },
  { name: "Theater", code: "THEATER" },
  { name: "Turkic Languages", code: "TURKIC" },
  { name: "Ukrainian", code: "UKRAIN" },
  { name: "University Studies", code: "UNIV ST" },
  { name: "Urban Planning", code: "URB PLAN" },
  { name: "Urology", code: "UROLOGY" },
  { name: "Vietnamese", code: "VIETNAM" },
  { name: "World Arts and Cultures", code: "WLD ARTS" },
  { name: "Yiddish", code: "YIDDISH" }
];

// Helper function to get department name by code - not currently used
export const getDepartmentName = (code) => {
  const dept = departments.find(d => d.code === code);
  return dept ? dept.name : code;
};

// Helper function to get department code by name - not currently used
export const getDepartmentCode = (name) => {
  const dept = departments.find(d => d.name === name);
  return dept ? dept.code : name;
};
