name: Deployment Status Check

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  check-deployment:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check Render Deployment
      run: |
        # Check if backend is responding
        echo "Testing backend deployment..."
        echo "Testing URL: https://peer-finding-network-ucla.onrender.com/"
        
        # First, try a simple GET request to see what we get
        echo "=== Testing with curl ==="
        curl -v https://peer-finding-network-ucla.onrender.com/ || echo "curl failed"
        
        echo "=== Testing with wget ==="
        wget --spider https://peer-finding-network-ucla.onrender.com/ && echo "wget succeeded" || echo "wget failed"
        
        echo "=== Testing with timeout ==="
        timeout 10 curl -f https://peer-finding-network-ucla.onrender.com/ && echo "✅ Backend is deployed and responding on Render" || echo "❌ Backend is not responding"
    
    - name: Report Status
      run: |
        echo "Deployment status: SUCCESS"
        echo "Backend URL: https://peer-finding-network-ucla.onrender.com" 